[2025-07-21T00:00:03.627+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-07-21T00:00:03.632+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-07-21T00:00:03.633+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-21T00:00:03.633+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-21T00:00:03.633+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-21T00:00:03.646+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-20 00:00:00+00:00
[2025-07-21T00:00:03.650+0000] {standard_task_runner.py:55} INFO - Started process 4846 to run task
[2025-07-21T00:00:03.656+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-20T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpul8x7umb']
[2025-07-21T00:00:03.666+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask feature_engineering
[2025-07-21T00:00:03.813+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [running]> on host e1a2c151e318
[2025-07-21T00:00:03.892+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-20T00:00:00+00:00
[2025-07-21T00:00:03.893+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-21T00:00:03.894+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-21T00:00:03.901+0000] {subprocess.py:86} INFO - Output:
[2025-07-21T00:00:04.935+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-21T00:00:04.935+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-21T00:00:04.936+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-21T00:00:04.943+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpqjw_5brj/data/raw/adult.csv …
[2025-07-21T00:00:04.943+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-21T00:00:04.991+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-21T00:00:04.991+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-21T00:00:04.991+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-21T00:00:04.992+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-21T00:00:04.992+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-21T00:00:04.992+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-21T00:00:04.992+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-21T00:00:04.994+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-21T00:00:04.995+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-21T00:00:04.995+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-21T00:00:04.995+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-21T00:00:04.996+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-21T00:00:04.998+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-21T00:00:04.998+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-21T00:00:04.999+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-21T00:00:04.999+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-21T00:00:04.999+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-21T00:00:04.999+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpqjw_5brj/data/raw/adult.csv'
[2025-07-21T00:00:05.000+0000] {subprocess.py:93} INFO - 
[2025-07-21T00:00:05.001+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-21T00:00:05.150+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-21T00:00:05.164+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-21T00:00:05.172+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250720T000000, start_date=20250721T000003, end_date=20250721T000005
[2025-07-21T00:00:05.181+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 15 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 4846)
[2025-07-21T00:00:05.223+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-21T00:00:05.245+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-21T08:07:45.520+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-07-21T08:07:45.528+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-07-21T08:07:45.528+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-21T08:07:45.528+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-21T08:07:45.528+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-21T08:07:45.536+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-20 00:00:00+00:00
[2025-07-21T08:07:45.539+0000] {standard_task_runner.py:55} INFO - Started process 256 to run task
[2025-07-21T08:07:45.541+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-20T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpve4rh_mo']
[2025-07-21T08:07:45.542+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-21T08:07:45.579+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [running]> on host af0370c7b194
[2025-07-21T08:07:45.616+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-20T00:00:00+00:00
[2025-07-21T08:07:45.617+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-21T08:07:45.617+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-21T08:07:45.624+0000] {subprocess.py:86} INFO - Output:
[2025-07-21T08:07:46.691+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-21T08:07:46.693+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-21T08:07:46.697+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-21T08:07:46.700+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpkpvtktbb/data/raw/adult.csv …
[2025-07-21T08:07:46.701+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-21T08:07:46.739+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-21T08:07:46.740+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-21T08:07:46.741+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpkpvtktbb/data/raw/adult.csv'
[2025-07-21T08:07:46.741+0000] {subprocess.py:93} INFO - 
[2025-07-21T08:07:46.741+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-21T08:07:46.861+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-21T08:07:46.871+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-21T08:07:46.875+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250720T000000, start_date=20250721T080745, end_date=20250721T080746
[2025-07-21T08:07:46.884+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 256)
[2025-07-21T08:07:46.902+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-21T08:07:46.915+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-21T12:26:11.526+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-07-21T12:26:11.537+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-07-21T12:26:11.537+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-21T12:26:11.538+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-21T12:26:11.538+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-21T12:26:11.570+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-20 00:00:00+00:00
[2025-07-21T12:26:11.575+0000] {standard_task_runner.py:55} INFO - Started process 251 to run task
[2025-07-21T12:26:11.576+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-20T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmphcttwm69']
[2025-07-21T12:26:11.579+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-21T12:26:11.623+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-20T00:00:00+00:00 [running]> on host a2f2a0c4e76e
[2025-07-21T12:26:11.658+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-20T00:00:00+00:00
[2025-07-21T12:26:11.658+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-21T12:26:11.659+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-21T12:26:11.664+0000] {subprocess.py:86} INFO - Output:
[2025-07-21T12:26:12.653+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-21T12:26:12.654+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-21T12:26:12.654+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-21T12:26:12.661+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpemsy20_o/data/raw/adult.csv …
[2025-07-21T12:26:12.661+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-21T12:26:12.699+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-21T12:26:12.699+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-21T12:26:12.699+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-21T12:26:12.699+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-21T12:26:12.700+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-21T12:26:12.701+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-21T12:26:12.701+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-21T12:26:12.701+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpemsy20_o/data/raw/adult.csv'
[2025-07-21T12:26:12.701+0000] {subprocess.py:93} INFO - 
[2025-07-21T12:26:12.701+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-21T12:26:12.830+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-21T12:26:12.841+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-21T12:26:12.847+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250720T000000, start_date=20250721T122611, end_date=20250721T122612
[2025-07-21T12:26:12.856+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 251)
[2025-07-21T12:26:12.865+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-21T12:26:12.882+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
