[2025-07-18T15:44:33.141+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering manual__2025-07-18T15:44:28.680469+00:00 [queued]>
[2025-07-18T15:44:33.146+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering manual__2025-07-18T15:44:28.680469+00:00 [queued]>
[2025-07-18T15:44:33.146+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:44:33.146+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T15:44:33.147+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:44:33.153+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-18 15:44:28.680469+00:00
[2025-07-18T15:44:33.156+0000] {standard_task_runner.py:55} INFO - Started process 252 to run task
[2025-07-18T15:44:33.159+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'manual__2025-07-18T15:44:28.680469+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpk7k1w560']
[2025-07-18T15:44:33.160+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask feature_engineering
[2025-07-18T15:44:33.191+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering manual__2025-07-18T15:44:28.680469+00:00 [running]> on host d7e53b8a5638
[2025-07-18T15:44:33.222+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-18T15:44:28.680469+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-18T15:44:28.680469+00:00
[2025-07-18T15:44:33.223+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:44:33.224+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:44:33.232+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:44:34.606+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:44:34.607+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:44:34.607+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:44:34.614+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpcn2x3741/data/raw/adult.csv â€¦
[2025-07-18T15:44:34.614+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:44:34.656+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:44:34.659+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:44:34.659+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:44:34.659+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:44:34.659+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:44:34.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:44:34.660+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:44:34.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:44:34.660+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:44:34.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:44:34.660+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:44:34.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpcn2x3741/data/raw/adult.csv'
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:44:34.661+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:44:34.760+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:44:34.769+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:44:34.772+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250718T154428, start_date=20250718T154433, end_date=20250718T154434
[2025-07-18T15:44:34.779+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 5 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 252)
[2025-07-18T15:44:34.822+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:44:34.836+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
